texture = "assets/images/player.png"
width = 64
height = 64
draw_offset = {x = 0.0, y = 0.0}

[idle]
row = 0
count = 2
speed = 1.5

[move]
row = 1
count = 2
speed = 8.0

[jump]
row = 2
count = 1
speed = 6.0

[melee_1]
row = 3
count = 2
speed = 5.714285714285714

[ranged_attack]
row = 4
count = 1
speed = 6.0
