speed = 200.0
jump_speed = 400.0
gravity = 980.0

[body]
offset = {w = 0.0, h = 40.0, d = 0.0}
radius = 36.0
start_angle = 155.0
angle = 50.0
color = {r = 0.941, g = 0.941, b = 0.941}
border = {thickness = 1.5, color = {r = 0.2, g = 0.2, b = 0.2}}

[head]
offset = {w = 0.0, h = 39.0, d = -0.1}
radius = 18.0
color = {r = 0.941, g = 0.941, b = 0.941}
border = {thickness = 1.5, color = {r = 0.2, g = 0.2, b = 0.2}}

[hand_front]
offset = {w = 9.0, h = 17.0, d = -0.3}
radius = 6.0
color = {r = 0.941, g = 0.941, b = 0.941}
border = {thickness = 1.0, color = {r = 0.2, g = 0.2, b = 0.2}}

[hand_back]
offset = {w = -10.0, h = 21.0, d = 0.3}
radius = 6.0
color = {r = 0.941, g = 0.941, b = 0.941}
border = {thickness = 1.0, color = {r = 0.2, g = 0.2, b = 0.2}}

[foot_left]
offset = {w = -8.0, h = 6.0, d = 0.2}
radius = 6.0
color = {r = 0.941, g = 0.941, b = 0.941}
border = {thickness = 1.0, color = {r = 0.2, g = 0.2, b = 0.2}}

[foot_right]
offset = {w = +8.0, h = 4.0, d = 0.2}
radius = 6.0
color = {r = 0.941, g = 0.941, b = 0.941}
border = {thickness = 1.0, color = {r = 0.2, g = 0.2, b = 0.2}}
