name: clang-format

on:
  push:
    branches:
      - main
    paths:
      - '**/*.cpp'
      - '**/*.hpp'
  pull_request:
    branches:
      - main
    paths:
      - '**/*.cpp'
      - '**/*.hpp'

env:
  LLVM_VERSION: 22.1.8

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install clang-format
        run: pipx install clang-format==${{ env.LLVM_VERSION }}
      - name: Check formatting
        run: |
          CLANG_FORMAT="$(pipx environment --value PIPX_BIN_DIR)/clang-format"
          "$CLANG_FORMAT" --version
          find Ash2/src Ash2/tests -name '*.cpp' -o -name '*.hpp' | \
          xargs "$CLANG_FORMAT" --dry-run --Werror
