name: clang-tidy

on:
  push:
    paths:
      - 'Ash2/src/**'
      - 'Ash2/tests/**'
      - '.clang-tidy'
      - '.github/workflows/clang-tidy.yml'
  pull_request:
    paths:
      - 'Ash2/src/**'
      - 'Ash2/tests/**'
      - '.clang-tidy'
      - '.github/workflows/clang-tidy.yml'

env:
  SIV3D_VERSION: 0.6.15

jobs:
  clang-tidy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Download Siv3D SDK
        run: |
          bitsadmin /transfer s3d-download "https://siv3d.jp/downloads/Siv3D/manual/${{ env.SIV3D_VERSION }}/OpenSiv3D_SDK_${{ env.SIV3D_VERSION }}.zip" "C:\OpenSiv3D_SDK.zip"
          Expand-Archive -Path "C:\OpenSiv3D_SDK.zip" -DestinationPath "C:"
          $varName = "SIV3D_" + "${{ env.SIV3D_VERSION }}".Replace(".", "_")
          $varValue = "C:\OpenSiv3D_SDK_${{ env.SIV3D_VERSION }}"
          echo "$varName=$varValue" >> $env:GITHUB_ENV
        shell: powershell

      - name: Run clang-tidy via MSBuild
        run: |
          msbuild Ash2/Ash2.sln `
            /p:Configuration=Debug `
            /p:Platform=x64 `
            /p:EnableClangTidyCodeAnalysis=True `
            /p:RunCodeAnalysis=True `
            /p:ClangTidyToolExe=clang-tidy.exe
        shell: powershell
